prefix oio: <http://www.geneontology.org/formats/oboInOwl#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?cls ?xref WHERE 
{
  ?cls a owl:Class ; 
     oio:hasDbXref ?xref .
    FILTER NOT EXISTS { ?cls owl:deprecated "true"^^xsd:boolean . }
    FILTER(isIRI(?cls) && STRSTARTS(str(?cls), "http://purl.obolibrary.org/obo/CL_") || STRSTARTS(str(?cls), "http://purl.obolibrary.org/obo/cl#"))
}
